# Generated by Django 3.0.5 on 2020-05-13 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_list_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='list',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
