# Generated by Django 3.0.4 on 2020-04-15 00:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
    ]
